-- Ported from the Bone catalog theme ayu.
local h = bone.hl.set
h('Normal', {fg = '#bfbdb6', bg = '#0b0e14'})
h('Dim', {fg = '#8a8f98'})
h('Accent', {fg = '#ffb454', bold = true})
h('UserPrompt', {fg = '#ffb454', bg = '#0b0e14', bold = true})
h('UserMessage', {fg = '#bfbdb6', bg = '#0b0e14'})
h('ToolName', {fg = '#bfbdb6'})
h('ToolArgs', {fg = '#8a8f98'})
h('ToolPath', {fg = '#ffb454'})
h('ToolOutput', {fg = '#8a8f98'})
h('Reasoning', {fg = '#565b66', italic = true})
h('DiffAdd', {fg = '#aad94c'})
h('DiffDelete', {fg = '#f07178'})
h('ShellProgram', {fg = '#aad94c'})
h('ShellPath', {fg = '#ffb454'})
h('ShellFlag', {fg = '#ffb454'})
h('ShellString', {fg = '#aad94c'})
h('ShellVariable', {fg = '#ffb454'})
h('ErrorMsg', {fg = '#f07178'})
h('WarningMsg', {fg = '#ffb454'})
h('Selection', {bg = '#1b202b'})
h('PopupBorder', {fg = '#252b37'})
h('PopupTitle', {fg = '#ffb454', bold = true})
h('StatusLine', {fg = '#bfbdb6', bold = true})
h('StatusLineDim', {fg = '#565b66'})
