-- Ported from the Bone catalog theme black.
local h = bone.hl.set
h('Normal', {fg = '#eeeeee', bg = '#000000'})
h('Dim', {fg = '#a0a0a0'})
h('Accent', {fg = '#7aa2f7', bold = true})
h('UserPrompt', {fg = '#7aa2f7', bg = '#000000', bold = true})
h('UserMessage', {fg = '#eeeeee', bg = '#000000'})
h('ToolName', {fg = '#eeeeee'})
h('ToolArgs', {fg = '#a0a0a0'})
h('ToolPath', {fg = '#7aa2f7'})
h('ToolOutput', {fg = '#a0a0a0'})
h('Reasoning', {fg = '#666666', italic = true})
h('DiffAdd', {fg = '#9ece6a'})
h('DiffDelete', {fg = '#f7768e'})
h('ShellProgram', {fg = '#9ece6a'})
h('ShellPath', {fg = '#7aa2f7'})
h('ShellFlag', {fg = '#7aa2f7'})
h('ShellString', {fg = '#9ece6a'})
h('ShellVariable', {fg = '#7aa2f7'})
h('ErrorMsg', {fg = '#f7768e'})
h('WarningMsg', {fg = '#e0af68'})
h('Selection', {bg = '#1a1a1a'})
h('PopupBorder', {fg = '#333333'})
h('PopupTitle', {fg = '#7aa2f7', bold = true})
h('StatusLine', {fg = '#eeeeee', bold = true})
h('StatusLineDim', {fg = '#666666'})
