-- Ported from the Bone catalog theme catppuccin.
local h = bone.hl.set
h('Normal', {fg = '#cdd6f4', bg = '#1e1e2e'})
h('Dim', {fg = '#a6adc8'})
h('Accent', {fg = '#cba6f7', bold = true})
h('UserPrompt', {fg = '#cba6f7', bg = '#1e1e2e', bold = true})
h('UserMessage', {fg = '#cdd6f4', bg = '#1e1e2e'})
h('ToolName', {fg = '#cdd6f4'})
h('ToolArgs', {fg = '#a6adc8'})
h('ToolPath', {fg = '#cba6f7'})
h('ToolOutput', {fg = '#a6adc8'})
h('Reasoning', {fg = '#6c7086', italic = true})
h('DiffAdd', {fg = '#a6e3a1'})
h('DiffDelete', {fg = '#f38ba8'})
h('ShellProgram', {fg = '#a6e3a1'})
h('ShellPath', {fg = '#cba6f7'})
h('ShellFlag', {fg = '#cba6f7'})
h('ShellString', {fg = '#a6e3a1'})
h('ShellVariable', {fg = '#cba6f7'})
h('ErrorMsg', {fg = '#f38ba8'})
h('WarningMsg', {fg = '#f9e2af'})
h('Selection', {bg = '#313244'})
h('PopupBorder', {fg = '#45475a'})
h('PopupTitle', {fg = '#cba6f7', bold = true})
h('StatusLine', {fg = '#cdd6f4', bold = true})
h('StatusLineDim', {fg = '#6c7086'})
