-- Ported from the Bone catalog theme dracula.
local h = bone.hl.set
h('Normal', {fg = '#f8f8f2', bg = '#171820'})
h('Dim', {fg = '#b9bac1'})
h('Accent', {fg = '#bd93f9', bold = true})
h('UserPrompt', {fg = '#bd93f9', bg = '#171820', bold = true})
h('UserMessage', {fg = '#f8f8f2', bg = '#171820'})
h('ToolName', {fg = '#f8f8f2'})
h('ToolArgs', {fg = '#b9bac1'})
h('ToolPath', {fg = '#bd93f9'})
h('ToolOutput', {fg = '#b9bac1'})
h('Reasoning', {fg = '#6272a4', italic = true})
h('DiffAdd', {fg = '#50fa7b'})
h('DiffDelete', {fg = '#ff5555'})
h('ShellProgram', {fg = '#50fa7b'})
h('ShellPath', {fg = '#bd93f9'})
h('ShellFlag', {fg = '#bd93f9'})
h('ShellString', {fg = '#50fa7b'})
h('ShellVariable', {fg = '#bd93f9'})
h('ErrorMsg', {fg = '#ff5555'})
h('WarningMsg', {fg = '#f1fa8c'})
h('Selection', {bg = '#44475a'})
h('PopupBorder', {fg = '#44475a'})
h('PopupTitle', {fg = '#bd93f9', bold = true})
h('StatusLine', {fg = '#f8f8f2', bold = true})
h('StatusLineDim', {fg = '#6272a4'})
