-- Ported from the Bone catalog theme gruvbox.
local h = bone.hl.set
h('Normal', {fg = '#ebdbb2', bg = '#181818'})
h('Dim', {fg = '#bdae93'})
h('Accent', {fg = '#fabd2f', bold = true})
h('UserPrompt', {fg = '#fabd2f', bg = '#181818', bold = true})
h('UserMessage', {fg = '#ebdbb2', bg = '#181818'})
h('ToolName', {fg = '#ebdbb2'})
h('ToolArgs', {fg = '#bdae93'})
h('ToolPath', {fg = '#fabd2f'})
h('ToolOutput', {fg = '#bdae93'})
h('Reasoning', {fg = '#665c54', italic = true})
h('DiffAdd', {fg = '#b8bb26'})
h('DiffDelete', {fg = '#fb4934'})
h('ShellProgram', {fg = '#b8bb26'})
h('ShellPath', {fg = '#fabd2f'})
h('ShellFlag', {fg = '#fabd2f'})
h('ShellString', {fg = '#b8bb26'})
h('ShellVariable', {fg = '#fabd2f'})
h('ErrorMsg', {fg = '#fb4934'})
h('WarningMsg', {fg = '#fe8019'})
h('Selection', {bg = '#3c3836'})
h('PopupBorder', {fg = '#504945'})
h('PopupTitle', {fg = '#fabd2f', bold = true})
h('StatusLine', {fg = '#ebdbb2', bold = true})
h('StatusLineDim', {fg = '#665c54'})
