-- Ported from the Bone catalog theme nord.
local h = bone.hl.set
h('Normal', {fg = '#eceff4', bg = '#1b1f26'})
h('Dim', {fg = '#d8dee9'})
h('Accent', {fg = '#88c0d0', bold = true})
h('UserPrompt', {fg = '#88c0d0', bg = '#1b1f26', bold = true})
h('UserMessage', {fg = '#eceff4', bg = '#1b1f26'})
h('ToolName', {fg = '#eceff4'})
h('ToolArgs', {fg = '#d8dee9'})
h('ToolPath', {fg = '#88c0d0'})
h('ToolOutput', {fg = '#d8dee9'})
h('Reasoning', {fg = '#4c566a', italic = true})
h('DiffAdd', {fg = '#a3be8c'})
h('DiffDelete', {fg = '#bf616a'})
h('ShellProgram', {fg = '#a3be8c'})
h('ShellPath', {fg = '#88c0d0'})
h('ShellFlag', {fg = '#88c0d0'})
h('ShellString', {fg = '#a3be8c'})
h('ShellVariable', {fg = '#88c0d0'})
h('ErrorMsg', {fg = '#bf616a'})
h('WarningMsg', {fg = '#ebcb8b'})
h('Selection', {bg = '#3b4252'})
h('PopupBorder', {fg = '#4c566a'})
h('PopupTitle', {fg = '#88c0d0', bold = true})
h('StatusLine', {fg = '#eceff4', bold = true})
h('StatusLineDim', {fg = '#4c566a'})
