-- Ported from the Bone catalog theme one-dark.
local h = bone.hl.set
h('Normal', {fg = '#abb2bf', bg = '#181b20'})
h('Dim', {fg = '#8b929e'})
h('Accent', {fg = '#61afef', bold = true})
h('UserPrompt', {fg = '#61afef', bg = '#181b20', bold = true})
h('UserMessage', {fg = '#abb2bf', bg = '#181b20'})
h('ToolName', {fg = '#abb2bf'})
h('ToolArgs', {fg = '#8b929e'})
h('ToolPath', {fg = '#61afef'})
h('ToolOutput', {fg = '#8b929e'})
h('Reasoning', {fg = '#5c6370', italic = true})
h('DiffAdd', {fg = '#98c379'})
h('DiffDelete', {fg = '#e06c75'})
h('ShellProgram', {fg = '#98c379'})
h('ShellPath', {fg = '#61afef'})
h('ShellFlag', {fg = '#61afef'})
h('ShellString', {fg = '#98c379'})
h('ShellVariable', {fg = '#61afef'})
h('ErrorMsg', {fg = '#e06c75'})
h('WarningMsg', {fg = '#e5c07b'})
h('Selection', {bg = '#353b45'})
h('PopupBorder', {fg = '#3e4451'})
h('PopupTitle', {fg = '#61afef', bold = true})
h('StatusLine', {fg = '#abb2bf', bold = true})
h('StatusLineDim', {fg = '#5c6370'})
