-- Ported from the Bone catalog theme rose-pine.
local h = bone.hl.set
h('Normal', {fg = '#e0def4', bg = '#191724'})
h('Dim', {fg = '#908caa'})
h('Accent', {fg = '#c4a7e7', bold = true})
h('UserPrompt', {fg = '#c4a7e7', bg = '#191724', bold = true})
h('UserMessage', {fg = '#e0def4', bg = '#191724'})
h('ToolName', {fg = '#e0def4'})
h('ToolArgs', {fg = '#908caa'})
h('ToolPath', {fg = '#c4a7e7'})
h('ToolOutput', {fg = '#908caa'})
h('Reasoning', {fg = '#6e6a86', italic = true})
h('DiffAdd', {fg = '#9ccfd8'})
h('DiffDelete', {fg = '#eb6f92'})
h('ShellProgram', {fg = '#9ccfd8'})
h('ShellPath', {fg = '#c4a7e7'})
h('ShellFlag', {fg = '#c4a7e7'})
h('ShellString', {fg = '#9ccfd8'})
h('ShellVariable', {fg = '#c4a7e7'})
h('ErrorMsg', {fg = '#eb6f92'})
h('WarningMsg', {fg = '#f6c177'})
h('Selection', {bg = '#26233a'})
h('PopupBorder', {fg = '#393552'})
h('PopupTitle', {fg = '#c4a7e7', bold = true})
h('StatusLine', {fg = '#e0def4', bold = true})
h('StatusLineDim', {fg = '#6e6a86'})
