-- Ported from the Bone catalog theme tokyo-night.
local h = bone.hl.set
h('Normal', {fg = '#c0caf5', bg = '#1a1b26'})
h('Dim', {fg = '#9aa5ce'})
h('Accent', {fg = '#7aa2f7', bold = true})
h('UserPrompt', {fg = '#7aa2f7', bg = '#1a1b26', bold = true})
h('UserMessage', {fg = '#c0caf5', bg = '#1a1b26'})
h('ToolName', {fg = '#c0caf5'})
h('ToolArgs', {fg = '#9aa5ce'})
h('ToolPath', {fg = '#7aa2f7'})
h('ToolOutput', {fg = '#9aa5ce'})
h('Reasoning', {fg = '#565f89', italic = true})
h('DiffAdd', {fg = '#9ece6a'})
h('DiffDelete', {fg = '#f7768e'})
h('ShellProgram', {fg = '#9ece6a'})
h('ShellPath', {fg = '#7aa2f7'})
h('ShellFlag', {fg = '#7aa2f7'})
h('ShellString', {fg = '#9ece6a'})
h('ShellVariable', {fg = '#7aa2f7'})
h('ErrorMsg', {fg = '#f7768e'})
h('WarningMsg', {fg = '#e0af68'})
h('Selection', {bg = '#292e42'})
h('PopupBorder', {fg = '#3b4261'})
h('PopupTitle', {fg = '#7aa2f7', bold = true})
h('StatusLine', {fg = '#c0caf5', bold = true})
h('StatusLineDim', {fg = '#565f89'})
